version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 12
  build:
    commands:
      - sam package --template-file template.yml --s3-bucket lambdas-zips-us-east-1-1337 --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml
